name: Build APK

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Create .env
        run: echo "EXPO_PUBLIC_WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" > .env

      - name: Expo prebuild
        run: npx expo prebuild --platform android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: weather-app-apk
          path: android/app/build/outputs/apk/release/app-release.apk
